[package]
name = "block_dictionary"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = { version = "2.10.0", features = ["serde"] }
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.12"
toml = "0.9.2"
